/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Pichau
 */
public class Calculadora extends javax.swing.JFrame {


    public Calculadora() {
        initComponents();
    }
double valor1, valor2, result;

String op;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b_menos = new javax.swing.JButton();
        b_multiplicação = new javax.swing.JButton();
        b_soma = new javax.swing.JButton();
        b_igual = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b_divisao = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b_virg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        Visor = new javax.swing.JTextField();
        historico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));

        Fundo.setBackground(new java.awt.Color(51, 51, 51));
        Fundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText(" Padrão");
        jLabel1.setToolTipText("");
        Fundo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 122, 40));

        jPanel1.setBackground(new java.awt.Color(47, 47, 47));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(51, 51, 51));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("up1");
        jButton17.setActionCommand("");
        jButton17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton17.setDefaultCapable(false);
        jButton17.setFocusable(false);
        jButton17.setPreferredSize(new java.awt.Dimension(78, 48));
        jButton17.setRolloverEnabled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton18.setBackground(new java.awt.Color(51, 51, 51));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("up2");
        jButton18.setActionCommand("");
        jButton18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton18.setDefaultCapable(false);
        jButton18.setFocusable(false);
        jButton18.setPreferredSize(new java.awt.Dimension(78, 48));
        jButton18.setRolloverEnabled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jButton19.setBackground(new java.awt.Color(51, 51, 51));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("up3");
        jButton19.setActionCommand("");
        jButton19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton19.setDefaultCapable(false);
        jButton19.setFocusable(false);
        jButton19.setPreferredSize(new java.awt.Dimension(78, 48));
        jButton19.setRolloverEnabled(false);
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        remove.setBackground(new java.awt.Color(102, 0, 0));
        remove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        remove.setForeground(new java.awt.Color(153, 0, 0));
        remove.setText("C");
        remove.setActionCommand("");
        remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        remove.setContentAreaFilled(false);
        remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remove.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        remove.setDefaultCapable(false);
        remove.setFocusable(false);
        remove.setPreferredSize(new java.awt.Dimension(78, 48));
        remove.setRolloverEnabled(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel1.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        b7.setBackground(new java.awt.Color(51, 51, 51));
        b7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.setActionCommand("");
        b7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b7.setContentAreaFilled(false);
        b7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b7.setDefaultCapable(false);
        b7.setFocusable(false);
        b7.setPreferredSize(new java.awt.Dimension(78, 48));
        b7.setRolloverEnabled(false);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        b8.setBackground(new java.awt.Color(51, 51, 51));
        b8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.setActionCommand("");
        b8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b8.setContentAreaFilled(false);
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b8.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b8.setDefaultCapable(false);
        b8.setFocusable(false);
        b8.setPreferredSize(new java.awt.Dimension(78, 48));
        b8.setRolloverEnabled(false);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        b9.setBackground(new java.awt.Color(51, 51, 51));
        b9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.setActionCommand("");
        b9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b9.setContentAreaFilled(false);
        b9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b9.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b9.setDefaultCapable(false);
        b9.setFocusable(false);
        b9.setPreferredSize(new java.awt.Dimension(78, 48));
        b9.setRolloverEnabled(false);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        b_menos.setBackground(new java.awt.Color(51, 51, 51));
        b_menos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_menos.setForeground(new java.awt.Color(153, 153, 153));
        b_menos.setText("-");
        b_menos.setActionCommand("");
        b_menos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b_menos.setContentAreaFilled(false);
        b_menos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_menos.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b_menos.setDefaultCapable(false);
        b_menos.setFocusable(false);
        b_menos.setPreferredSize(new java.awt.Dimension(78, 48));
        b_menos.setRolloverEnabled(false);
        b_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menosActionPerformed(evt);
            }
        });
        jPanel1.add(b_menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        b_multiplicação.setBackground(new java.awt.Color(51, 51, 51));
        b_multiplicação.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_multiplicação.setForeground(new java.awt.Color(153, 153, 153));
        b_multiplicação.setText("x");
        b_multiplicação.setActionCommand("");
        b_multiplicação.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b_multiplicação.setContentAreaFilled(false);
        b_multiplicação.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_multiplicação.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b_multiplicação.setDefaultCapable(false);
        b_multiplicação.setFocusable(false);
        b_multiplicação.setPreferredSize(new java.awt.Dimension(78, 48));
        b_multiplicação.setRolloverEnabled(false);
        b_multiplicação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_multiplicaçãoActionPerformed(evt);
            }
        });
        jPanel1.add(b_multiplicação, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        b_soma.setBackground(new java.awt.Color(51, 51, 51));
        b_soma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_soma.setForeground(new java.awt.Color(153, 153, 153));
        b_soma.setText("+");
        b_soma.setActionCommand("");
        b_soma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b_soma.setContentAreaFilled(false);
        b_soma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_soma.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b_soma.setDefaultCapable(false);
        b_soma.setFocusable(false);
        b_soma.setPreferredSize(new java.awt.Dimension(78, 48));
        b_soma.setRolloverEnabled(false);
        b_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_somaActionPerformed(evt);
            }
        });
        jPanel1.add(b_soma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        b_igual.setBackground(new java.awt.Color(51, 51, 51));
        b_igual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_igual.setForeground(new java.awt.Color(153, 153, 153));
        b_igual.setText("=");
        b_igual.setActionCommand("");
        b_igual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b_igual.setContentAreaFilled(false);
        b_igual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_igual.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b_igual.setDefaultCapable(false);
        b_igual.setFocusable(false);
        b_igual.setPreferredSize(new java.awt.Dimension(78, 48));
        b_igual.setRolloverEnabled(false);
        b_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_igualActionPerformed(evt);
            }
        });
        jPanel1.add(b_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        b4.setBackground(new java.awt.Color(51, 51, 51));
        b4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.setActionCommand("");
        b4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b4.setContentAreaFilled(false);
        b4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b4.setDefaultCapable(false);
        b4.setFocusable(false);
        b4.setPreferredSize(new java.awt.Dimension(78, 48));
        b4.setRolloverEnabled(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        b5.setBackground(new java.awt.Color(51, 51, 51));
        b5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.setActionCommand("");
        b5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b5.setContentAreaFilled(false);
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b5.setDefaultCapable(false);
        b5.setFocusable(false);
        b5.setPreferredSize(new java.awt.Dimension(78, 48));
        b5.setRolloverEnabled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        b6.setBackground(new java.awt.Color(51, 51, 51));
        b6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.setActionCommand("");
        b6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b6.setContentAreaFilled(false);
        b6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b6.setDefaultCapable(false);
        b6.setFocusable(false);
        b6.setPreferredSize(new java.awt.Dimension(78, 48));
        b6.setRolloverEnabled(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        b1.setBackground(new java.awt.Color(51, 51, 51));
        b1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.setActionCommand("");
        b1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b1.setContentAreaFilled(false);
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b1.setDefaultCapable(false);
        b1.setFocusable(false);
        b1.setPreferredSize(new java.awt.Dimension(78, 48));
        b1.setRolloverEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        b2.setBackground(new java.awt.Color(51, 51, 51));
        b2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.setActionCommand("");
        b2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b2.setContentAreaFilled(false);
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b2.setDefaultCapable(false);
        b2.setFocusable(false);
        b2.setPreferredSize(new java.awt.Dimension(78, 48));
        b2.setRolloverEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        b3.setBackground(new java.awt.Color(51, 51, 51));
        b3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.setActionCommand("");
        b3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b3.setContentAreaFilled(false);
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b3.setDefaultCapable(false);
        b3.setFocusable(false);
        b3.setPreferredSize(new java.awt.Dimension(78, 48));
        b3.setRolloverEnabled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        b_divisao.setBackground(new java.awt.Color(51, 51, 51));
        b_divisao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_divisao.setForeground(new java.awt.Color(153, 153, 153));
        b_divisao.setText("/");
        b_divisao.setActionCommand("");
        b_divisao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b_divisao.setContentAreaFilled(false);
        b_divisao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_divisao.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b_divisao.setDefaultCapable(false);
        b_divisao.setFocusable(false);
        b_divisao.setPreferredSize(new java.awt.Dimension(78, 48));
        b_divisao.setRolloverEnabled(false);
        b_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_divisaoActionPerformed(evt);
            }
        });
        jPanel1.add(b_divisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        b0.setBackground(new java.awt.Color(51, 51, 51));
        b0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.setActionCommand("");
        b0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b0.setContentAreaFilled(false);
        b0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b0.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b0.setDefaultCapable(false);
        b0.setFocusable(false);
        b0.setPreferredSize(new java.awt.Dimension(78, 48));
        b0.setRolloverEnabled(false);
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        b_virg.setBackground(new java.awt.Color(51, 51, 51));
        b_virg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        b_virg.setForeground(new java.awt.Color(153, 153, 153));
        b_virg.setText(",");
        b_virg.setActionCommand("");
        b_virg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        b_virg.setContentAreaFilled(false);
        b_virg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_virg.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        b_virg.setDefaultCapable(false);
        b_virg.setFocusable(false);
        b_virg.setPreferredSize(new java.awt.Dimension(78, 48));
        b_virg.setRolloverEnabled(false);
        b_virg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_virgActionPerformed(evt);
            }
        });
        jPanel1.add(b_virg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadora/caneca-de-cafe (3).png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 280));

        label1.setBackground(new java.awt.Color(47, 47, 47));
        label1.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        label1.setText(" By: Gabriel Andrade Corrêa");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));
        label1.getAccessibleContext().setAccessibleDescription("");

        Fundo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 370, 320));

        Visor.setBackground(new java.awt.Color(51, 51, 51));
        Visor.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Visor.setForeground(new java.awt.Color(204, 204, 204));
        Visor.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Visor.setBorder(null);
        Visor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisorActionPerformed(evt);
            }
        });
        Fundo.add(Visor, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 153, 331, 63));

        historico.setBackground(new java.awt.Color(51, 51, 51));
        historico.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        historico.setForeground(new java.awt.Color(102, 102, 102));
        historico.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        historico.setBorder(null);
        historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicoActionPerformed(evt);
            }
        });
        Fundo.add(historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 335, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// 7
    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
  Visor.setText(Visor.getText()+"7");
    }//GEN-LAST:event_b7ActionPerformed
// TELA Visor
    private void VisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisorActionPerformed

    }//GEN-LAST:event_VisorActionPerformed
// BOTÃO UP1 (FUTURA ATUALIZAÇÃO)
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

    }//GEN-LAST:event_jButton17ActionPerformed
// DIVISÃO /
    private void b_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_divisaoActionPerformed
valor1=Double.parseDouble(Visor.getText());
op = "divisao"; // 4 = DIVISÂO
Visor.setText("");
historico.setText(String.valueOf(valor1 + " /"));
    }//GEN-LAST:event_b_divisaoActionPerformed
// 8
    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
     Visor.setText(Visor.getText()+"8"); 
    }//GEN-LAST:event_b8ActionPerformed
// 2
    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
 Visor.setText(Visor.getText()+"2");
    }//GEN-LAST:event_b2ActionPerformed
// 1
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
 Visor.setText(Visor.getText()+"1");       
    }//GEN-LAST:event_b1ActionPerformed
// 3
    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
 Visor.setText(Visor.getText()+"3");
    }//GEN-LAST:event_b3ActionPerformed
// 4
    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
 Visor.setText(Visor.getText()+"4");
    }//GEN-LAST:event_b4ActionPerformed
// 5
    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
 Visor.setText(Visor.getText()+"5");
    }//GEN-LAST:event_b5ActionPerformed
// 6
    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
 Visor.setText(Visor.getText()+"6");
    }//GEN-LAST:event_b6ActionPerformed
// 9 
    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
 Visor.setText(Visor.getText()+"9");
    }//GEN-LAST:event_b9ActionPerformed
// 0
    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
 Visor.setText(Visor.getText()+"0");
    }//GEN-LAST:event_b0ActionPerformed
// REMOVER  C
    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
 Visor.setText("");
 historico.setText("");
    }//GEN-LAST:event_removeActionPerformed
// SOMA +
    private void b_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_somaActionPerformed
valor1 = Double.parseDouble(Visor.getText());
op = "soma"; // 1 = SOMA
Visor.setText("");
historico.setText(String.valueOf(valor1 + " +")); // HISTORICO RECEBE O VALOR1 E O SIMBOLO +
    }//GEN-LAST:event_b_somaActionPerformed
// MULTIPLICAÇÃO X
    private void b_multiplicaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_multiplicaçãoActionPerformed
valor1 = Double.parseDouble(Visor.getText());
Visor.setText("");
op = "multiplicacao"; // 2 = MULTIPLICAÇÃO
historico.setText(String.valueOf(valor1)+(" x "));// HISTORICO RECEBE O VALOR1 E O SIMBOLO X

    }//GEN-LAST:event_b_multiplicaçãoActionPerformed
// IGUAL =
    private void b_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_igualActionPerformed
valor2 = Double.parseDouble(Visor.getText());
System.out.println("VALOR 1:" + valor1);
System.out.println("VALOR 2:" + valor2);
switch(op){
    case "soma": result = valor1+valor2;System.out.println("OPERAÇÃO + E RESULTADO:" + result);break;
    case "multiplicacao": result =valor1*valor2;System.out.println("OPERAÇÃO * E RESULTADO:" + result);break;   
    case "menos": result = valor1-valor2;System.out.println("OPERAÇÃO - E RESULTADO :" + result);break;
    case "divisao": result =valor1/valor2;System.out.println("OPERAÇÃO / E RESULTADO:" + result);break;
    default:Visor.setText("DEU RUIM");System.out.println("DEU RUIM");break;
} System.out.println("TESTE RESULTADO LINHA 699: " + result);
Visor.setText(String.valueOf(result));
historico.setText("");// APAGA HISTORICO
    }//GEN-LAST:event_b_igualActionPerformed

    private void b_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menosActionPerformed
valor1 = Double.parseDouble(Visor.getText());
op = "menos"; // 3 = MENOS
Visor.setText(""); // VISOR É APAGADO
historico.setText(String.valueOf(valor1 + " -")); // HISTORICO RECEBE VALOR1 E SIMBOLO -
    }//GEN-LAST:event_b_menosActionPerformed

    private void historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoActionPerformed

    }//GEN-LAST:event_historicoActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void b_virgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_virgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_virgActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fundo;
    private javax.swing.JTextField Visor;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton b_divisao;
    private javax.swing.JButton b_igual;
    private javax.swing.JButton b_menos;
    private javax.swing.JButton b_multiplicação;
    private javax.swing.JButton b_soma;
    private javax.swing.JButton b_virg;
    private javax.swing.JTextField historico;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
